import Head from 'next/head';
import { useAppContext } from '@/context/state';

const Logout = () => {
  const { deleteSession } = useAppContext();
  deleteSession();

  return (
    <Head>
      <title>Logout</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Logout;
