import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAppContext } from '@/context/state';

export default function Home() {
  const router = useRouter();
  const { token } = useAppContext();

  useEffect(() => {
    if(token === '') router.push('/login') 
  }, [])
  
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>        
        test
      </div>
    </>
  );
}
